Repository tmbo/questionary, pull requests merged in 2020-10, with the labels that each got.

#59 Document multiline input for devs and users
  .travis.yml
  questionary/constants.py
  questionary/prompts/text.py
  tests/test_question.py
  tests/utils.py
Labels: Documentation, Enhancement

#60 Accept style tuples in `title` argument annotation of `Choice`
  questionary/prompts/common.py
Labels: Bug

#56 Add `initial_choice` for select and checkbox prompts
  questionary/prompts/checkbox.py
  questionary/prompts/common.py
  questionary/prompts/select.py
  tests/prompts/test_checkbox.py
  tests/prompts/test_select.py
Labels: Enhancement

#52 Removed check for choices if completer is present
  questionary/prompts/autocomplete.py
Labels: Awaiting response, Bug

#67 New build system
  .github/depandabot.yml
  .github/workflows/continous-integration.yml
  .gitignore
  .travis.yml
  Makefile
  README.md
  poetry.lock
  pyproject.toml
  questionary/prompt.py
  questionary/prompts/autocomplete.py
  questionary/prompts/checkbox.py
  questionary/prompts/common.py
  questionary/prompts/confirm.py
  questionary/prompts/password.py
  questionary/prompts/rawselect.py
  questionary/prompts/select.py
  questionary/prompts/text.py
  requirements.txt
  requirements_dev.txt
  scripts/validate_version.py
  setup.py
Labels: Enhancement

#69 Install Python version from matrix
  .github/workflows/continous-integration.yml
Labels: Bug

#72 Indicate the multiline input with \n>
  questionary/constants.py
Labels: Enhancement

#70 Allow passing in a custom lexer
  questionary/prompts/text.py
Labels: Enhancement

#71 Less restrictive python 3 dependency
  .github/workflows/continous-integration.yml
  pyproject.toml
Labels: Enhancement

#68 Increase type coverage
  questionary/__init__.py
  questionary/constants.py
  questionary/form.py
  questionary/prompt.py
  questionary/prompts/autocomplete.py
  questionary/prompts/checkbox.py
  questionary/prompts/common.py
  questionary/prompts/confirm.py
  questionary/prompts/password.py
  questionary/prompts/rawselect.py
  questionary/prompts/select.py
  questionary/prompts/text.py
  questionary/question.py
  questionary/utils.py
Labels: Enhancement
